### ISSUE TITLE
一点细节~

### ISSUE THREAD

**Issue by icepie** [Pililink/GIWIFI-demo-Login#1]
看到 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456` 咱应该要想到是 `base64` 编码 直接套用道哥的代码的话, 某些密码长度会算错的哦~

好的 咱学以致用一下, 欢迎加入组织

```
dGcgZ3JvdXA6IGh0dHBzOi8vdC5tZS9naXdpZmkKcXEgZ3JvdXA6IDc4OTc4MTgxOA==
```

**Comment by Pililink** [comment]
我之前写这个的时候没有注意这些，只是为了能跑起来。

**Comment by icepie** [comment]
> 我之前写这个的时候没有注意这些，只是为了能跑起来。

 hxd 加入一下组织细聊熬, 期待你的到来!
